volumes:
  keycloak_data:
  postgres_backend:
    driver: local

services:
  keycloak:
    image: quay.io/keycloak/keycloak:22.0.1
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - keycloak_data:/opt/keycloak/data/
    command:
      - start-dev

  postgres_backend:
      image: postgres:16.1
      env_file:
        - .env
      ports:
        - '5432:5432'
      volumes:
        - postgres_backend:/var/lib/postgresql/data
      healthcheck:
        test: [ "CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'" ]
        interval: 10s
        timeout: 3s
        retries: 3
